In [10]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 500
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(length, 1)))
model.add(Dense(length))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 30        
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
X

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [12]:
y

array([[0. , 0.2, 0.4, 0.6, 0.8]])

In [3]:
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=2)


Epoch 1/500
1/1 - 0s - loss: 0.2830
Epoch 2/500
1/1 - 0s - loss: 0.2805
Epoch 3/500
1/1 - 0s - loss: 0.2780
Epoch 4/500
1/1 - 0s - loss: 0.2756
Epoch 5/500
1/1 - 0s - loss: 0.2731
Epoch 6/500
1/1 - 0s - loss: 0.2707
Epoch 7/500
1/1 - 0s - loss: 0.2683
Epoch 8/500
1/1 - 0s - loss: 0.2660
Epoch 9/500
1/1 - 0s - loss: 0.2636
Epoch 10/500
1/1 - 0s - loss: 0.2612
Epoch 11/500
1/1 - 0s - loss: 0.2589
Epoch 12/500
1/1 - 0s - loss: 0.2566
Epoch 13/500
1/1 - 0s - loss: 0.2543
Epoch 14/500
1/1 - 0s - loss: 0.2520
Epoch 15/500
1/1 - 0s - loss: 0.2497
Epoch 16/500
1/1 - 0s - loss: 0.2475
Epoch 17/500
1/1 - 0s - loss: 0.2452
Epoch 18/500
1/1 - 0s - loss: 0.2430
Epoch 19/500
1/1 - 0s - loss: 0.2408
Epoch 20/500
1/1 - 0s - loss: 0.2385
Epoch 21/500
1/1 - 0s - loss: 0.2363
Epoch 22/500
1/1 - 0s - loss: 0.2342
Epoch 23/500
1/1 - 0s - loss: 0.2320
Epoch 24/500
1/1 - 0s - loss: 0.2298
Epoch 25/500
1/1 - 0s - loss: 0.2276
Epoch 26/500
1/1 - 0s - loss: 0.2255
Epoch 27/500
1/1 - 0s - loss: 0.2233
Epoch 28/5

In [4]:
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:]:
	print('%.1f' % value)

0.0
0.2
0.4
0.6
0.8


In [5]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.layers import LSTM
# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(length, 1), return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 5, 5)              140       
_________________________________________________________________
time_distributed (TimeDistri (None, 5, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
X

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [9]:
y

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [6]:
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=2)


Epoch 1/1000
1/1 - 0s - loss: 0.2355
Epoch 2/1000
1/1 - 0s - loss: 0.2321
Epoch 3/1000
1/1 - 0s - loss: 0.2287
Epoch 4/1000
1/1 - 0s - loss: 0.2253
Epoch 5/1000
1/1 - 0s - loss: 0.2220
Epoch 6/1000
1/1 - 0s - loss: 0.2187
Epoch 7/1000
1/1 - 0s - loss: 0.2154
Epoch 8/1000
1/1 - 0s - loss: 0.2122
Epoch 9/1000
1/1 - 0s - loss: 0.2090
Epoch 10/1000
1/1 - 0s - loss: 0.2058
Epoch 11/1000
1/1 - 0s - loss: 0.2027
Epoch 12/1000
1/1 - 0s - loss: 0.1996
Epoch 13/1000
1/1 - 0s - loss: 0.1965
Epoch 14/1000
1/1 - 0s - loss: 0.1935
Epoch 15/1000
1/1 - 0s - loss: 0.1905
Epoch 16/1000
1/1 - 0s - loss: 0.1876
Epoch 17/1000
1/1 - 0s - loss: 0.1846
Epoch 18/1000
1/1 - 0s - loss: 0.1817
Epoch 19/1000
1/1 - 0s - loss: 0.1788
Epoch 20/1000
1/1 - 0s - loss: 0.1760
Epoch 21/1000
1/1 - 0s - loss: 0.1732
Epoch 22/1000
1/1 - 0s - loss: 0.1704
Epoch 23/1000
1/1 - 0s - loss: 0.1676
Epoch 24/1000
1/1 - 0s - loss: 0.1649
Epoch 25/1000
1/1 - 0s - loss: 0.1622
Epoch 26/1000
1/1 - 0s - loss: 0.1595
Epoch 27/1000
1/1 - 0

In [7]:
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:,0]:
	print('%.1f' % value)

0.1
0.2
0.4
0.6
0.8
